name: release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o cwbackup-tui_${{ matrix.goos }}_${{ matrix.goarch }} ./cmd/cwbackup-tui

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cwbackup-tui_${{ matrix.goos }}_${{ matrix.goarch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
